/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import bbdd.ConexionDgonzalez;
import java.awt.Insets;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import modelo.PacienteDgonzalez;
import utilidades.EncriptadoDgonzalez;
import utilidades.UtilidadesDgonzalez;

/**
 *
 * @author David
 */
public class MedicoDgonzalez extends javax.swing.JFrame {

    public static String DniPacienteDgonzalez;
    public static String nombrePacienteDgonzalez;
    public static String apellidosPacienteDgonzalez;
    public static String emailPacienteDgonzalez;
    /**
     * Creates new form MedicoDgonzalezz
     */
    public MedicoDgonzalez() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campoDni = new javax.swing.JTextField();
        botonPaciente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoApellidos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        botonInforme = new javax.swing.JButton();
        botonCita = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        botonTabla = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1175, 650));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI PACIENTE");

        botonPaciente.setBackground(new java.awt.Color(0, 0, 0));
        botonPaciente.setForeground(new java.awt.Color(255, 255, 255));
        botonPaciente.setText("BUSCAR PACIENTE");
        botonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacienteActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");

        campoNombre.setEnabled(false);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellidos");

        campoApellidos.setEnabled(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");

        campoTelefono.setEnabled(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Email");

        campoEmail.setEnabled(false);

        botonInforme.setText("Nuevo informe");
        botonInforme.setEnabled(false);
        botonInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformeActionPerformed(evt);
            }
        });

        botonCita.setText("Nuevo Cita");
        botonCita.setEnabled(false);
        botonCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonInforme)
                        .addGap(118, 118, 118)
                        .addComponent(botonCita)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInforme)
                    .addComponent(botonCita))
                .addGap(16, 16, 16))
        );

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("HISTORIAL DE CONSULTAS MÉDICAS");

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "DIAGNÓSTICO", "TRATAMIENTO", "OBSERVACIONES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaconsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaconsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaconsulta);

        botonTabla.setText("Actualizar Tabla");
        botonTabla.setEnabled(false);
        botonTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(botonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(botonTabla)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPaciente))
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botonTabla)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo_good.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("CONSULTA MÉDICA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacienteActionPerformed
        try {
            DniPacienteDgonzalez = campoDni.getText();
            nombrePacienteDgonzalez = campoNombre.getText();
            apellidosPacienteDgonzalez = campoApellidos.getText();
            comprobarDniDgonzalez();
            DefaultTableModel modelo = (DefaultTableModel) tablaconsulta.getModel();
            ConexionDgonzalez.conectarDgonzalez();
            ConexionDgonzalez.cargaTablaConsultasMedicasDgonzalez(modelo, EncriptadoDgonzalez.encriptarDgonzalez(campoDni.getText()));
            ConexionDgonzalez.cerrarConexionDgonzalez();

        } catch (InvalidKeyException | NoSuchAlgorithmException | IllegalBlockSizeException | NoSuchPaddingException | BadPaddingException ex) {
            Logger.getLogger(MedicoDgonzalez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonPacienteActionPerformed

    private void botonInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformeActionPerformed
        NuevaConsultaMedicoDgonzalez ncm = new NuevaConsultaMedicoDgonzalez();
        ncm.setVisible(true);
    }//GEN-LAST:event_botonInformeActionPerformed

    private void botonCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCitaActionPerformed
        DniPacienteDgonzalez = campoDni.getText();
        nombrePacienteDgonzalez = campoNombre.getText();
        apellidosPacienteDgonzalez = campoApellidos.getText();
        emailPacienteDgonzalez = campoEmail.getText();
        NuevaCitaDgonzalez nc = new NuevaCitaDgonzalez(this, true);
        nc.setVisible(true);
    }//GEN-LAST:event_botonCitaActionPerformed

    private void botonTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTablaActionPerformed
        try {
            DefaultTableModel modelo = (DefaultTableModel) tablaconsulta.getModel();
            modelo.setRowCount(0);
            ConexionDgonzalez.conectarDgonzalez();
            ConexionDgonzalez.cargaTablaConsultasMedicasDgonzalez(modelo, EncriptadoDgonzalez.encriptarDgonzalez(campoDni.getText()));
            ConexionDgonzalez.cerrarConexionDgonzalez();
        } catch (InvalidKeyException | NoSuchAlgorithmException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
            Logger.getLogger(MedicoDgonzalez.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonTablaActionPerformed

    private void tablaconsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaconsultaMouseClicked
        datosFilaDgonzalez();
    }//GEN-LAST:event_tablaconsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoDgonzalez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoDgonzalez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoDgonzalez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoDgonzalez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicoDgonzalez().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCita;
    private javax.swing.JButton botonInforme;
    private javax.swing.JButton botonPaciente;
    private javax.swing.JButton botonTabla;
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoDni;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables

    public void comprobarDniDgonzalez() throws InvalidKeyException, NoSuchAlgorithmException, IllegalBlockSizeException, NoSuchPaddingException, BadPaddingException {
        {
            String valorDNIDgonzalez = campoDni.getText();
            String valorDNIEncripDgonzalez = EncriptadoDgonzalez.encriptarDgonzalez(valorDNIDgonzalez);

            if (UtilidadesDgonzalez.formatoDniCorrectoDgonzalez(campoDni) && UtilidadesDgonzalez.letraDniCorrectaDgonzalez(campoDni)) {
                ConexionDgonzalez.conectarDgonzalez();
                if (ConexionDgonzalez.compruebaDniDgonzalez(valorDNIEncripDgonzalez)) {
                    PacienteDgonzalez paciente = ConexionDgonzalez.recuperaDatosPacienteDgonzalez(valorDNIEncripDgonzalez);
                    campoNombre.setText(EncriptadoDgonzalez.desencriptarDgonzalez(paciente.getNombreDgonzalez()));
                    campoApellidos.setText(EncriptadoDgonzalez.desencriptarDgonzalez(paciente.getApellidosDgonzalez()));
                    campoTelefono.setText(String.valueOf(paciente.getTelefonoDgonzalez()));
                    campoEmail.setText(paciente.getEmailDgonzalez());
                    ConexionDgonzalez.cerrarConexionDgonzalez();
                    campoDni.setEnabled(false);
                    botonInforme.setEnabled(true);
                    botonCita.setEnabled(true);
                    botonTabla.setEnabled(true);

                    DniPacienteDgonzalez = campoDni.getText();
                } else {
                    // Si no esta registrado el DNI.
                    JOptionPane.showMessageDialog(this, "No existe paciente con este DNI\n"
                            + "a continuación se abrira la ventana para crearlo.");
                    NuevoPacienteDgonzalez np = new NuevoPacienteDgonzalez(this, true);
                    np.setVisible(true);

                }
            } else {
                // Alertas de lo que va mal
                ConexionDgonzalez.conectarDgonzalez();
                if (!UtilidadesDgonzalez.formatoDniCorrectoDgonzalez(campoDni)) {
                    UtilidadesDgonzalez.lanzaAlertaDniDgonzalez(null, campoDni);
                    ConexionDgonzalez.cerrarConexionDgonzalez();
                } else {
                    UtilidadesDgonzalez.lanzaAlertaLetraDniDgonzalez(null, campoDni);
                    ConexionDgonzalez.cerrarConexionDgonzalez();
                }
            }
        }
    }

    private void datosFilaDgonzalez() {

        String contenido = "FECHA DE CONSULTA: " + String.valueOf(tablaconsulta.getValueAt(tablaconsulta.getSelectedRow(), 0));
        contenido += "\n\nDIAGNÓSTICO:\n " + String.valueOf(tablaconsulta.getValueAt(tablaconsulta.getSelectedRow(), 1));
        contenido += "\n\nTRATAMIENTO:\n " + String.valueOf(tablaconsulta.getValueAt(tablaconsulta.getSelectedRow(), 2));
        contenido += "\n\nOBSERVACIONES:\n " + String.valueOf(tablaconsulta.getValueAt(tablaconsulta.getSelectedRow(), 3));

        JTextArea t = new JTextArea(20, 60);
        t.setText(contenido);
        t.setEditable(false);
        t.setLineWrap(true);
        t.setFocusable(false);
        t.setAutoscrolls(true);
        t.setMargin(new Insets(10, 10, 10, 10));

        JOptionPane.showMessageDialog(this, new JScrollPane(t), "INFORME", 1);

    }

}
